### ISSUE TITLE
"note is a duplicate" error

### ISSUE THREAD

**Issue by archelpeg** [Pseudonium/Obsidian_to_Anki#134]
I get this error and can't add new notes.

![grafik](https://user-images.githubusercontent.com/72164229/101988520-64e08d00-3c9a-11eb-9806-a255e341bbab.png)

That's what I want to add.

![grafik](https://user-images.githubusercontent.com/72164229/101988665-4a5ae380-3c9b-11eb-8d3d-1af1e5ee61c8.png)

**Comment by Pseudonium** [comment]
Hmm, do you have any notes with the same front field in Anki already? I.e. do you have any duplicates?

**Comment by Pseudonium** [comment]
Oh, nevermind, I've run into this same error! I think I figured out what was causing this, it'll be fixed for next release.

**Comment by archelpeg** [comment]
I didn't have duplicates.

Thanks! :)

**Comment by raphaelhuleux** [comment]
Hi, I have the same issue (without using Obisidian):

```
Traceback (most recent call last):
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1777, in <module>
    main()
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 217, in main
    App()
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 974, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1707, in parse_requests_1
    file.note_ids = [
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1708, in <listcomp>
    AnkiConnect.parse(response)
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 245, in parse
    raise Exception(response['error'])
Exception: cannot create note because it is a duplicate
``
