### ISSUE TITLE
setup script 404

### ISSUE THREAD

**Issue by Goondrious** [Pseudonium/Obsidian_to_Anki#218]
tyvm for this project. Have been using on my PC for awhile. Setting up on mac os laptop I found:

- Latest couples releases don't include SCRIPT_URL & REQUIRE_URL files, so `obstoanki_setup.py` fails with HTTP 404
  - e.g. https://github.com/Pseudonium/Obsidian_to_Anki/releases/tag/3.4.1

```
 python3 obstoanki_setup.py 
Traceback (most recent call last):
  File "obstoanki_setup.py", line 20, in <module>
    with urllib.request.urlopen(SCRIPT_URL) as script:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Fixed locally by changing url to the last tag with the files.

**Comment by raphaelhuleux** [comment]
Same issue.
