### ISSUE TITLE
Exception: cannot create note because it is a duplicate

### ISSUE THREAD

**Issue by raphaelhuleux** [Pseudonium/Obsidian_to_Anki#224]
Hi,

I get the following error while running the script. I don't know which note creates the issue but I don't believe I have any duplicate. 

```
Traceback (most recent call last):
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1777, in <module>
    main()
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 217, in main
    App()
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 974, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1707, in parse_requests_1
    file.note_ids = [
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 1708, in <listcomp>
    AnkiConnect.parse(response)
  File "/Users/raphaelhuleux/Documents/Projects/markdown_scripts/obisidan_to_anki/obsidian_to_anki.py", line 245, in parse
    raise Exception(response['error'])
Exception: cannot create note because it is a duplicate
``

**Comment by kebifurai** [comment]
Card duplicates are not generated with the obsidian-to-anki plugin as well.
