### ISSUE TITLE
20201015 Error when run scripts

### ISSUE THREAD

**Issue by EngineerLeonJ** [Pseudonium/Obsidian_to_Anki#79]
Error Message
```
Traceback (most recent call last):
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 1561, in <module>
    main()
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 187, in main
    App()
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 917, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 1500, in parse_requests_1
    file.card_ids = AnkiConnect.parse(card_ids)
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 215, in parse
    raise Exception(response['error'])
Exception
```

**Comment by EngineerLeonJ** [comment]
I dont' know why, but i delete the config file and remake it, now there is no error message, but still some markdown files not recognized.
202010150745
202010150743
202010150741

[ObsdianLibrary.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5382407/ObsdianLibrary.zip)

**Comment by EngineerLeonJ** [comment]
error again:
```
Traceback (most recent call last):
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 1561, in <module>
    main()
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 187, in main
    App()
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 917, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 1500, in parse_requests_1
    file.card_ids = AnkiConnect.parse(card_ids)
  File "C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py", line 215, in parse
    raise Exception(response['error'])
Exception

```

config file:
```
[Basic]
Front = Front:
Back = Back:

[Basic (and reversed card)]
Front = Front:
Back = Back:

[Basic (optional reversed card)]
Front = Front:
Back = Back:
Add Reverse = Add Reverse:

[Basic (type in the answer)]
Front = Front:
Back = Back:

[Cloze]
Text = Text:
Back Extra = Back Extra:

[Note Substitutions]
Basic = Basic
Basic (and reversed card) = Basic (and reversed card)
Basic (optional reversed card) = Basic (optional reversed card)
Basic (type in the answer) = Basic (type in the answer)
Cloze = Cloze

[Cloze Note Types]
Basic = False
Basic (and reversed card) = False
Basic (optional reversed card) = False
Basic (type in the answer) = False
Cloze = True

[Syntax]
Begin Note = START
End Note = END
Begin Inline Note = STARTI
End Inline Note = ENDI
Target Deck Line = TARGET DECK
File Tags Line = FILE TAGS
Delete Regex Note Line = DELETE

[Obsidian]
Vault name = ObsdianLibrary
Add file link = True

[Defaults]
Tag = Obsidian_to_Anki
Deck = Inbox
CurlyCloze = False
GUI = True
Regex = False
ID Comments = True
Anki Path = C:\Program Files\Anki\anki.exe
Anki Profile = User 1

[Custom Regexps]
Basic = ^Q: ((?:[^\n][\n]?)+)\n+A: ((?:[^\n][\n]?)+)
Basic (and reversed card) = 
Basic (optional reversed card) = 
Basic (type in the answer) = 
Cloze = 

[Added Media]


```

**Comment by EngineerLeonJ** [comment]
I removed all the ids in markdown files (anki cards kept), then sync again, now it works well without error message.
Only one issue:
the new markdown text recognized and came into anki, but it seems that ids were not added to markdown text:
![image](https://user-images.githubusercontent.com/50700790/96085803-6bd56400-0ed2-11eb-9c1a-0c46b21c8086.png)
