### ISSUE TITLE
msvc9compiler.py can't find vcvarsall

### ISSUE THREAD

**Issue by SubZeroX** [Pseudonium/Obsidian_to_Anki#85]
Hey,

When I try to run the obstoanki_setup.py, I'm getting this error:

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Gab\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gab\\AppData\\Local\\Temp\\pip-install-hr1d5j6a\\wxpython\\setup.py'"'"'; __file__='"'"'C:\\Users\\Gab\\AppData\\Local\\Temp\\pip-install-hr1d5j6a\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Gab\AppData\Local\Temp\pip-record-rbfq_8m1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Gab\AppData\Local\Programs\Python\Python39\Include\wxpython'
         cwd: C:\Users\Gab\AppData\Local\Temp\pip-install-hr1d5j6a\wxpython\
    Complete output (27 lines):
    running install
    running build
    Will build using: "C:\Users\Gab\AppData\Local\Programs\Python\Python39\python.exe"
    3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
    Python's architecture is 64bit
    cfg.VERSION: 4.0.7

    Running command: build
    Running command: build_wx
    Command '"C:\Users\Gab\AppData\Local\Programs\Python\Python39\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gab\AppData\Local\Programs\Python\Python39\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Users\Gab\AppData\Local\Programs\Python\Python39\lib\distutils\msvc9compiler.py", line 260, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
    Finished command: build_wx (0.78s)
    Finished command: build (0.78s)
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "C:\Users\Gab\AppData\Local\Programs\Python\Python39\python.exe" -u build.py build
    Command '"C:\Users\Gab\AppData\Local\Programs\Python\Python39\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Gab\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gab\\AppData\\Local\\Temp\\pip-install-hr1d5j6a\\wxpython\\setup.py'"'"'; __file__='"'"'C:\\Users\\Gab\\AppData\\Local\\Temp\\pip-install-hr1d5j6a\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Gab\AppData\Local\Temp\pip-record-rbfq_8m1\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Gab\AppData\Local\Programs\Python\Python39\Include\wxpython' Check the logs for full command output.
``` 

What can I do?

Windows 10 64bits Pro Version
Python 3.9
Pip 20.2.4

**Comment by Pseudonium** [comment]
Ah, could you run a `pip freeze` for me! Looks like Gooey is causing trouble again...

**Comment by martinsondergaard** [comment]
I have the same problem. It seems that Gooey depends on wxpython==4.0.7, but there are no wheels available for that specific version on Windows. At the same time I can't get Python 3.9 and distutils to recognize the Visual Studio C++ compiler, which causes the error above to happen when trying to build wxpython.

**Comment by Pseudonium** [comment]
That’s odd - I run windows myself and I’ve never had a problem with gooey...

**Comment by Pseudonium** [comment]
@SubZeroX if you're still interested, you could try out the obsidian plugin, which would solve this issue.

**Comment by SubZeroX** [comment]
> @SubZeroX if you're still interested, you could try out the obsidian plugin, which would solve this issue.

Heyy, yeap. The plugin solved all problems. Thanks!
