### ISSUE TITLE
Unable to execute obstoanki_setup.py

### ISSUE THREAD

**Issue by sdirge** [Pseudonium/Obsidian_to_Anki#91]
Hi, I am having difficulty running the install script. The system is Win10 x64 build 2004 with Python 3.9.0 installed.

The output from the obstoanki_setup.py is below:

Hi, I am having difficulty running the install script. The system is Win10 x64 build 2004 with Python 3.9.0 installed.

The output from the obstoanki_setup.py is below:

```
PS C:\temp\ObstoAnki> .\obstoanki_setup.py
Collecting Gooey==1.0.4.0.0.0
  Using cached Gooey-1.0.4.0.0.0-py2.py3-none-any.whl (617 kB)
Collecting Markdown==3.2.2
  Using cached Markdown-3.2.2-py3-none-any.whl (88 kB)
Requirement already satisfied: Pillow>=4.3.0 in c:\users\someusername\appdata\local\programs\python\python39\lib\site-packages (from Gooey==1.0.4.0.0.0->-r obstoankirequire.txt (line 1)) (8.0.1)
Requirement already satisfied: psutil>=5.4.2 in c:\users\someusername\appdata\local\programs\python\python39\lib\site-packages (from Gooey==1.0.4.0.0.0->-r obstoankirequire.txt (line 1)) (5.7.3)
Requirement already satisfied: colored>=1.3.93 in c:\users\someusername\appdata\local\programs\python\python39\lib\site-packages (from Gooey==1.0.4.0.0.0->-r obstoankirequire.txt (line 1)) (1.4.2)
Collecting wxpython==4.0.7
  Using cached wxPython-4.0.7.tar.gz (68.9 MB)
Requirement already satisfied: six in c:\users\someusername\appdata\local\programs\python\python39\lib\site-packages (from wxpython==4.0.7->Gooey==1.0.4.0.0.0->-r obstoankirequire.txt (line 1)) (1.15.0)
Requirement already satisfied: numpy in c:\users\someusername\appdata\local\programs\python\python39\lib\site-packages (from wxpython==4.0.7->Gooey==1.0.4.0.0.0->-r obstoankirequire.txt (line 1)) (1.19.4)
Using legacy 'setup.py install' for wxpython, since package 'wheel' is not installed.
Installing collected packages: wxpython, Gooey, Markdown
    Running setup.py install for wxpython ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\someusername\\AppData\\Local\\Temp\\pip-install-qalobcx9\\wxpython\\setup.py'"'"'; __file__='"'"'C:\\Users\\someusername\\AppData\\Local\\Temp\\pip-install-qalobcx9\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\someusername\AppData\Local\Temp\pip-record-p3cg07wl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\someusername\AppData\Local\Programs\Python\Python39\Include\wxpython'
         cwd: C:\Users\someusername\AppData\Local\Temp\pip-install-qalobcx9\wxpython\
    Complete output (27 lines):
    running install
    running build
    Will build using: "C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe"
    3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
    Python's architecture is 64bit
    cfg.VERSION: 4.0.7

    Running command: build
    Running command: build_wx
    Command '"C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\someusername\AppData\Local\Programs\Python\Python39\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Users\someusername\AppData\Local\Programs\Python\Python39\lib\distutils\msvc9compiler.py", line 260, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
    Finished command: build_wx (0.61s)
    Finished command: build (0.61s)
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe" -u build.py build
    Command '"C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\someusername\\AppData\\Local\\Temp\\pip-install-qalobcx9\\wxpython\\setup.py'"'"'; __file__='"'"'C:\\Users\\someusername\\AppData\\Local\\Temp\\pip-install-qalobcx9\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\someusername\AppData\Local\Temp\pip-record-p3cg07wl\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\someusername\AppData\Local\Programs\Python\Python39\Include\wxpython' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\someusername\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\temp\ObstoAnki\obstoanki_setup.py", line 27, in <module>
    subprocess.check_call(
  File "C:\Users\someusername\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\someusername\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', 'install', '-r', 'obstoankirequire.txt']' returned non-zero exit status 1.
PS C:\temp\ObstoAnki> Get-WindowsVersion
```

Any help would be appreciated.

**Comment by sdirge** [comment]
I was able to get the script installed by ignoring the issues with gooey.
