### ISSUE TITLE
Error while converting a note with embed /transcluded content

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#97]
I get the following error when trying to make note from a paragraph which is succeeded by a transcluded content.

PLease see if can be fixed :)

PS Thnks for the script! :) 
```
PageName%20WordAfterASpace%20WordAfterASpace%20(1967)#%5Eae427e
Traceback (most recent call last):
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 1561, in <module>
    main()
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 187, in main
    App()
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 872, in __init__
    Directory(root, regex=args.regex)
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 1441, in __init__
    file.scan_file()
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 1311, in scan_file
    self.search(note_type, regexp)
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 1372, in search
    parsed = RegexNote(match, note_type, tags=False, id=False).parse(
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 625, in parse
    template["fields"] = self.fields
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 609, in fields
    fields = {
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 610, in <dictcomp>
    key: FormatConverter.format(
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 395, in format
    FormatConverter.get_images(note_text)
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 328, in get_images
    MEDIA[filename] = file_encode(path)
  File "C:\Users\DummyMe\Desktop\Obsidian_to_Anki-2.9.0\obsidian_to_anki.py", line 104, in file_encode
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'PageName%20WordAfterASpace%20WordAfterASpace%20(1967)#%5Eae427e'

```

**Comment by Pseudonium** [comment]
Could you show me the actual file?

**Comment by dummifiedme** [comment]
I will share the file. But its irrespective of the file. Whenever there is an embed in the file via. `![[.       ]] `, the script throws an error.

**Comment by Pseudonium** [comment]
That's odd, I've run the script on files with embeds just fine. Or are you trying to embed something inside a flashcard? In which case that's classed as unsupported.

**Comment by dummifiedme** [comment]
I will look for the exact case that I was trying back then, and get back. 😅

**Comment by Pseudonium** [comment]
Suggestion - check out the new Obsidian plugin version of the script. I handle Obsidian image embeds too in that version, so hopefully this error won't occur.

**Comment by dummifiedme** [comment]
I checked the Plugin as soon as I woke up, lol.
And, I didn't know how to run it. Is it through crtl+P commands? And will
it work for the note opened there or for all the files in my vault?

**Comment by dummifiedme** [comment]
The plugin solves this issue 👍
